version: "3.0"
services:
  api:
    image: xtrime/telegram-api-server:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    init: true
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "127.0.0.1:9503:9503"
    volumes:
      - ./:/app-host-link
    working_dir: /app-host-link
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "2"
    command:
      - "-s=session"
  mysql:
    image: mariadb:11.1
    restart: unless-stopped
    ports:
      - "127.0.0.1:9507:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_AUTO_UPGRADE: 'yes'
    command:
     - --skip-grant-tables
     - --innodb-buffer-pool-size=128M
     - --wait_timeout=65

networks:
    host:
        name: host
        external: true
